apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: ${NAME}
spec:
  designerFlowsOperationMode: disabled
  license:
    accept: true
    license: ${LICENSE}
    use: ${LICENSE_USE}
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: ${SERVICE_ENDPOINT_TYPE}
  useCommonServices: true
  version: ${VERSION}
  adminServerSecure: true
  pod:
    containers:
      runtime:
        image: ${IMAGE}
        imagePullPolicy: Always
